"""add_items_idx_user_id

Revision ID: 6ad43e418042
Revises: 8a68ec046abe
Create Date: 2024-10-20 19:28:29.253819

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ad43e418042"
down_revision: Union[str, None] = "8a68ec046abe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_items_user_id"), "items", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_user_id"), table_name="items")
    # ### end Alembic commands ###
